# Generated by Django 6.1.1 on 2026-09-20 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('weekly_contact_hours', models.PositiveIntegerField(default=4)),
                ('total_enrolled_students', models.PositiveIntegerField(default=0)),
                ('assessment_weight', models.IntegerField(choices=[(1, 'Standard / MCQ (1.0x)'), (2, 'Practical / Labs / Coding (2.0x)'), (3, 'Heavy Essays / Research Projects (3.0x)')], default=2)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='users.department')),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_modules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(max_length=20)),
                ('module_name', models.CharField(max_length=200)),
                ('credit_units', models.FloatField(default=3.0)),
                ('student_count', models.PositiveIntegerField(default=0)),
                ('difficulty_weight', models.FloatField(default=1.0)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_assignments', to='users.lecturerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WorkloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimester_name', models.CharField(default='2026-T1', max_length=20)),
                ('week_number', models.PositiveIntegerField(default=1)),
                ('teaching_hours', models.FloatField(default=0.0)),
                ('grading_backlog_days', models.PositiveIntegerField(default=0)),
                ('supervised_theses', models.PositiveIntegerField(default=0)),
                ('weekend_work_hours', models.FloatField(default=0.0)),
                ('lms_late_night_actions', models.PositiveIntegerField(default=0)),
                ('modules_count', models.PositiveIntegerField(default=0)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('assessment_weight', models.FloatField(default=1.5)),
                ('assignments_to_grade', models.PositiveIntegerField(default=0)),
                ('hod_admin_hours', models.FloatField(default=0.0)),
                ('active_research_projects', models.PositiveIntegerField(default=0)),
                ('self_reported_fatigue', models.PositiveIntegerField(default=5, help_text='Rating from 1 (Fresh) to 10 (Exhausted)')),
                ('perceived_support', models.PositiveIntegerField(default=3, help_text='Rating from 1 (Poor Support) to 5 (Excellent Support)')),
                ('predicted_weekly_hours', models.FloatField(default=0.0)),
                ('burnout_risk_score', models.FloatField(default=0.0, help_text='Calculated percentage (0 to 100%)')),
                ('burnout_risk_category', models.CharField(choices=[('LOW', 'Low Risk (0-35%)'), ('MODERATE', 'Moderate Strain (36-55%)'), ('HIGH', 'High Risk (56-75%)'), ('CRITICAL', 'Critical Overload (>75%)')], default='LOW', max_length=20)),
                ('recommended_action', models.TextField(blank=True, help_text='AI-generated recommendation for HOD / Lecturer', null=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workload_logs', to='users.lecturerprofile')),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='BurnoutPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_weekly_hours', models.FloatField()),
                ('burnout_risk_score', models.FloatField(help_text='Calculated percentage (0 to 100%)')),
                ('risk_category', models.CharField(choices=[('LOW', 'Low Risk (0-35%)'), ('MODERATE', 'Moderate Strain (36-55%)'), ('HIGH', 'High Risk (56-75%)'), ('CRITICAL', 'Critical Overload (>75%)')], max_length=20)),
                ('recommended_action', models.TextField(blank=True, help_text='AI-generated recommendation for HOD / Lecturer', null=True)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('workload_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='workload.workloadlog')),
            ],
        ),
    ]
