# Generated by Django 6.1.1 on 2026-09-22 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('workload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturerLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('classes_affected', models.PositiveIntegerField(default=0)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_records', to='users.lecturerprofile')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
